module(
    name = "tao3k_site",
    version = "0.1.0",
)

bazel_dep(name = "gerbil_bazel", version = "0.1.0")
bazel_dep(name = "poo_flow", version = "0.1.0")

git_override(
    module_name = "gerbil_bazel",
    commit = "faa83024b7fa6f681bf3bd0da57376e05fb9a2f7",
    remote = "https://github.com/tao3k/gerbil-bazel.git",
)

git_override(
    module_name = "poo_flow",
    commit = "7f60e82b609ed2227ce3e71d17c5a1a351902e54",
    remote = "https://github.com/tao3k/poo-flow.git",
)

gerbil = use_extension("@gerbil_bazel//gerbil:extensions.bzl", "gerbil")
use_repo(gerbil, "local_gerbil")
