/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRouteImport } from './routes/api'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeploymentRouteImport } from './routes/deployment'
import { Route as DepoymentRouteImport } from './routes/depoyment'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as OpenSourceRouteImport } from './routes/open-source'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as SolutionsRouteImport } from './routes/solutions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentRoute = DeploymentRouteImport.update({
  id: '/deployment',
  path: '/deployment',
  getParentRoute: () => rootRouteImport,
} as any)
const DepoymentRoute = DepoymentRouteImport.update({
  id: '/depoyment',
  path: '/depoyment',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenSourceRoute = OpenSourceRouteImport.update({
  id: '/open-source',
  path: '/open-source',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/contact': typeof ContactRoute
  '/deployment': typeof DeploymentRoute
  '/depoyment': typeof DepoymentRoute
  '/enterprise': typeof EnterpriseRoute
  '/open-source': typeof OpenSourceRoute
  '/platform': typeof PlatformRoute
  '/research': typeof ResearchRoute
  '/solutions': typeof SolutionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/contact': typeof ContactRoute
  '/deployment': typeof DeploymentRoute
  '/depoyment': typeof DepoymentRoute
  '/enterprise': typeof EnterpriseRoute
  '/open-source': typeof OpenSourceRoute
  '/platform': typeof PlatformRoute
  '/research': typeof ResearchRoute
  '/solutions': typeof SolutionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/contact': typeof ContactRoute
  '/deployment': typeof DeploymentRoute
  '/depoyment': typeof DepoymentRoute
  '/enterprise': typeof EnterpriseRoute
  '/open-source': typeof OpenSourceRoute
  '/platform': typeof PlatformRoute
  '/research': typeof ResearchRoute
  '/solutions': typeof SolutionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api'
    | '/contact'
    | '/deployment'
    | '/depoyment'
    | '/enterprise'
    | '/open-source'
    | '/platform'
    | '/research'
    | '/solutions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api'
    | '/contact'
    | '/deployment'
    | '/depoyment'
    | '/enterprise'
    | '/open-source'
    | '/platform'
    | '/research'
    | '/solutions'
  id:
    | '__root__'
    | '/'
    | '/api'
    | '/contact'
    | '/deployment'
    | '/depoyment'
    | '/enterprise'
    | '/open-source'
    | '/platform'
    | '/research'
    | '/solutions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRoute: typeof ApiRoute
  ContactRoute: typeof ContactRoute
  DeploymentRoute: typeof DeploymentRoute
  DepoymentRoute: typeof DepoymentRoute
  EnterpriseRoute: typeof EnterpriseRoute
  OpenSourceRoute: typeof OpenSourceRoute
  PlatformRoute: typeof PlatformRoute
  ResearchRoute: typeof ResearchRoute
  SolutionsRoute: typeof SolutionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployment': {
      id: '/deployment'
      path: '/deployment'
      fullPath: '/deployment'
      preLoaderRoute: typeof DeploymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depoyment': {
      id: '/depoyment'
      path: '/depoyment'
      fullPath: '/depoyment'
      preLoaderRoute: typeof DepoymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-source': {
      id: '/open-source'
      path: '/open-source'
      fullPath: '/open-source'
      preLoaderRoute: typeof OpenSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRoute: ApiRoute,
  ContactRoute: ContactRoute,
  DeploymentRoute: DeploymentRoute,
  DepoymentRoute: DepoymentRoute,
  EnterpriseRoute: EnterpriseRoute,
  OpenSourceRoute: OpenSourceRoute,
  PlatformRoute: PlatformRoute,
  ResearchRoute: ResearchRoute,
  SolutionsRoute: SolutionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
